CREATE TABLE IF NOT EXISTS metadata(key TEXT PRIMARY KEY, value BLOB NOT NULL);
CREATE TABLE IF NOT EXISTS owners(id TEXT PRIMARY KEY, password_hash TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sessions(hash TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES owners(id), csrf TEXT NOT NULL, expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS devices(id TEXT PRIMARY KEY, label TEXT NOT NULL, revoked INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS invitations(hash TEXT PRIMARY KEY, device_id TEXT NOT NULL REFERENCES devices(id), expires INTEGER NOT NULL, used INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS services(id TEXT PRIMARY KEY, label TEXT NOT NULL, base_url TEXT NOT NULL, revision INTEGER NOT NULL DEFAULT 1, enabled INTEGER NOT NULL DEFAULT 1, auth TEXT NOT NULL, credential BLOB NOT NULL, auth_header TEXT NOT NULL DEFAULT '', request_headers TEXT NOT NULL DEFAULT '["Accept","Content-Type"]', response_headers TEXT NOT NULL DEFAULT '["Content-Type","Content-Encoding","Retry-After"]', private_cidr TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS permissions(id TEXT PRIMARY KEY, device_id TEXT NOT NULL REFERENCES devices(id), service_id TEXT NOT NULL REFERENCES services(id), revision INTEGER NOT NULL, method TEXT NOT NULL, path TEXT NOT NULL, path_kind TEXT NOT NULL DEFAULT 'exact', mode TEXT NOT NULL DEFAULT 'standing', created_by_owner_id TEXT NOT NULL REFERENCES owners(id), created_at INTEGER NOT NULL DEFAULT (unixepoch()), expires INTEGER, revoked INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS audit(id INTEGER PRIMARY KEY, time INTEGER NOT NULL DEFAULT (unixepoch()), owner_id TEXT NOT NULL, device_id TEXT NOT NULL, kind TEXT NOT NULL, entity_id TEXT NOT NULL);

